language: c
sudo: false

env:
  global:
    - RACKET_DIR=~/racket
    - PACKAGE_NAME=racket-language-server
  matrix:
    - RACKET_VERSION=6.12

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - mkdir $(pwd)/xdg-runtime-dir
  - export XDG_RUNTIME_DIR="$(pwd)/xdg-runtime-dir"

script:
  - raco pkg install --deps search-auto
  - raco setup --check-pkg-deps $PACKAGE_NAME
  - raco make main.rkt
  - xvfb-run raco test -p $PACKAGE_NAME
